# Site settings
title: Quantitative Magnetic Resonance Imaging in Pediatric Brains
lab_name: Weber Lab
author: >
  Alex Weber but borrowed heavily from the Morin laboratory: https://morinlab.github.io
institution: UBC and BCCHR
email: aweber@bcchr.ca
description: >
  The Weber Lab is interested in using and improving quantiative MRI methods to look at 
  the healthy and disordered brain in pediatric populations.
baseurl: ""
url: "https://weberlab.github.io"
twitter_username: AlexMarkWeber
github_username:  weberam2
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
